---
language: csharp
solution: MaxMind.Db.sln

env:
  global:
    - MAXMIND_BENCHMARK_DB=$TRAVIS_BUILD_DIR/MaxMind.Db.Test/TestData/MaxMind-DB/test-data/GeoIP2-City-Test.mmdb
    - MAXMIND_TEST_BASE_DIR=$TRAVIS_BUILD_DIR/MaxMind.Db.Test
    - CONFIGURATION=Release

matrix:
  include:
  - os: linux
    dotnet: 3.1
    mono: none
    sudo: required
    env: DOTNETCORE=1 CONSOLE_FRAMEWORK=netcoreapp3.1
  - os: osx
    dotnet: 3.1.100
    mono: none
    env: DOTNETCORE=1 CONSOLE_FRAMEWORK=netcoreapp3.1
  - os: linux
    mono: latest
    sudo: false

install: git submodule update --init --recursive

script: ./dev-bin/build.sh

notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "Squj/3RvcTEfCK72Jw5Zzdgk9whWZJAP/n7mqD08siCq1uu5ZRZLLGrawYjKPXwkafmX5MCbmqF6pGOtvnupRiHNWkaY4br7hclkqUCerZi5QROuFOKChKTu7lVxzZkU0e/d+0Ujfqb+1VVPm+oahfZKZ/eG61Em3klKo7sEfig=\n"
